# np.meshgrid()

在计算机中进行绘图操作时，往往需要一些采样点，然后根据这些采样点绘制出整个图形

In [6]:
import numpy as np
x = np.arange(1, 4)
y = np.arange(6, 8)
X, Y = np.meshgrid(x, y)
print(x, y, sep='\n\n')
print()
print(X, Y, sep='\n\n')

[1 2 3]

[6 7]

[[1 2 3]
 [1 2 3]]

[[6 6 6]
 [7 7 7]]


`meshgrid`将`x`当作行向量复制了`len(y)`次变成一个`(2, 3)`的矩阵

`meshgrid`将`y`当作列向量复制了`len(x)`次变成一个`(2, 3)`的矩阵

`X,Y`中存放着xoy平面中采样点的`x,y`坐标

也就是我们要在1<=x<=3,6<=y<=7的平面内绘制图形，则需要表示出的坐标为：

(1,6)，(2,6)，(3,6)

(1,7)，(2,7)，(3,7)

把各个点的x坐标独立出来就是X中的数据：

1，2，3

1，2，3

再把各个点的y坐标独立出来就是Y中的数据：

6，6，6

7，7，7

# np.r_和np.c_

- `np.r_`添加到第一个维度

- `np.c_`添加到最后一个维度


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 0, 0], [1, 1, 1]])
print(np.r_[a, b])
print()
print(np.c_[a, b])

[[1 2 3]
 [4 5 6]
 [0 0 0]
 [1 1 1]]

[[1 2 3 0 0 0]
 [4 5 6 1 1 1]]


In [11]:
a = np.zeros(3)
b = np.ones(3)
print(a.shape, b.shape)
print(np.r_[a, b].shape, np.c_[a, b].shape)

a = np.zeros((2, 3))
b = np.ones((2, 3))
print(a.shape, b.shape)
print(np.r_[a, b].shape, np.c_[a, b].shape)

a = np.zeros((2, 3, 4))
b = np.ones((2, 3, 4))
print(a.shape, b.shape)
print(np.r_[a, b].shape, np.c_[a, b].shape)

(3,) (3,)
(6,) (3, 2)
(2, 3) (2, 3)
(4, 3) (2, 6)
(2, 3, 4) (2, 3, 4)
(4, 3, 4) (2, 3, 8)


# np.random.uniform
- `random.uniform(参数1，参数2)` 返回参数1和参数2之间的任意值

In [2]:
import numpy as np
np.random.uniform(3, 10, 5)

array([4.39027761, 7.34022424, 7.28731143, 9.88894867, 5.32135218])

# np.random.multivariate_normal

- `def multivariate_normal(mean, cov, size=None, check_valid=None, tol=None)`从多元正态分布中生成随机抽样，组成一个N维的数组。并返回该数组。
 - `mean`：多元正态分布的维度。(长度为N的一维数组)
 - `cov`：多元正态分布的协方差矩阵，且协方差矩阵必须是对称矩阵和半正定矩阵(形状为(N,N)的二维数组)。
 - `size`：数组的形状（整数或者由整数构成的元组）。如果该值未给定，则返回单个N维的样本（N恰恰是上面mean的长度）。
  - `check_valid`：当协方差(上面的cov)矩阵不是半正定矩阵时，程序的处理方式（一共有三种方式：{ ‘warn’, ‘raise’, ‘ignore’ }）。igore:忽略协方差矩阵不是半正定矩阵的问题，生成数组。warn:输出警告，但是还是会生成数组。raise:程序报错，且不会生成数组
  - `tol`:当协方差矩阵只有一个值时，生成的公差（浮点数）。

In [4]:
np.random.multivariate_normal(np.random.randn(2), np.eye(2), (2, 2))

array([[[-0.82391543, -0.90725102],
        [ 0.22400312, -0.83353517]],

       [[ 0.07476064,  0.5790277 ],
        [ 0.04620254, -2.63115561]]])

In [5]:
np.random.randn(2)

array([-0.37064095,  0.33178886])