# 线性代数
Numpy定义了`matrix`类型， 使用该`matrix`类型创建的是矩阵对象，它们的加减乘除运算缺省采用矩阵方式计算，因此用法和Matblab十分类似。但是由于Numpy中同时存在`ndarray和matrix`对象，因此用户很容易将两者弄混。这有违Python的“显示优于隐藏”的原则，因此官方并不推荐在程序中使用`matrix`。在这里，我们仍然用`ndarray`来介绍

## 矩阵和向量积

矩阵的定义、矩阵的加法、矩阵的乘法、矩阵的转置与二维数组完全一致，不再进行说明，但矩阵的乘法有不同的表示。

- `numpy.dot(a, b[, out])` 计算两个矩阵的乘积，如果是一维数组则是它们的内积

【例】

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4 ,5, 6])
z = np.dot(x, y)
print(z)

x = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
print(x)

y = np.array([[5, 4, 2], [1, 7, 9], [0, 4, 5]])
print(y)

print(np.dot(x, y))

print(np.dot(y, x))

70
[[1 2 3]
 [3 4 5]
 [6 7 8]]
[[5 4 2]
 [1 7 9]
 [0 4 5]]
[[  7  30  35]
 [ 19  60  67]
 [ 37 105 115]]
[[ 29  40  51]
 [ 76  93 110]
 [ 42  51  60]]


【注意】：

在线性代数里面讲的维数和数组的维数不同，如线代中提到的n维行向量在Numpy中是一维数组，而线代中的n维列向量在Numpy中是一个shape为(n, 1)的二维数组


## 矩阵特征值与特征向量

- `numpy.linalg.eig(a)` 计算方阵的特征值和特征向量
- `numpy.linalg.eigvals(a)` 计算方阵的特征值

In [2]:
#创建一个对角矩阵
x = np.diag((1, 2, 3))
print(x)
# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]

print(np.linalg.eigvals(x))# [1. 2. 3.]

a, b = np.linalg.eig(x)
print(a) # [1. 2. 3.]
print(b)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

#检验特征值与特征向量是否正确
for i in range(x.shape[0]):
    if np.allclose(a[i] * b[:, i], np.dot(x, b[:, i])):
        print('Right')
    else:
        print('Error')

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1. 2. 3.]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Right
Right
Right


【例】判断对称阵是否为正定阵（特征值是否全部为正）

In [3]:
A = np.arange(16).reshape(4, 4)
print(A)

A = A + A.T # 转化成对称矩阵
print(A)

B = np.linalg.eigvals(A)
print(B)

if np.all(B > 0):
    print('Yes')
else:
    print('No')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[ 6.74165739e+01+0.00000000e+00j -7.41657387e+00+0.00000000e+00j
 -8.88285420e-17+1.82759332e-15j -8.88285420e-17-1.82759332e-15j]
No


# 矩阵分解

## 奇异值分解

有关奇异值分解的原理：[奇异值分解（SVD）及其应用](https://mp.weixin.qq.com/s/GNHPamltnqaUpGG9NhvWxg)

- u, s, v = numpy.linalg.svd(a, full_matrices = True, compute_uv = True, hermitian = False)` 奇异值分解
    - `a` 是一个形如(M, N)矩阵

    - `full_matrices` 的取值是为False或者True，默认值为True，这时`u`的大小为(M, M)，`v`的大小为(N, N))。否则`u`的大小为(M, K), `v`的大小为(K, N), K = min(M, N)

    - `comptue_uv`的取值是为False或者True，默认值为True，表示计算`u, s, v`为False的时候只计算`s`
    
    - 总共有三个返回值`u, s, v, u`大小为(M, M), `s`大小为(M, N), `v`大小为(N, N), `a = u * s * v`

    - 其中`s`是对矩阵`a`的奇异值分解。`s`除了对角元素不为`0`，其他元素都为`0`，并且对角元素从大到小排序。`s`中有`n`个奇异值，一般排在后面的比较接近0，所以仅保留比较大的`r`个奇异值。

【注】：Numpy中返回的`v`是通常所谓奇异值分解`a = u * s * v`中`v`的转置

In [4]:
A = np.array([[4, 11, 14], [8, 7, -2]])
print(A)
# [[ 4 11 14]
#  [ 8  7 -2]]

u, s, vh = np.linalg.svd(A, full_matrices = False)
print(u.shape)
print(u)
# [[-0.9486833  -0.31622777]
#  [-0.31622777  0.9486833 ]]

print(s.shape)
print(np.diag(s))
# [18.97366596  0.        ]
#  [ 0.          9.48683298]]

print(vh.shape)
print(vh)
# [[-0.33333333 -0.66666667 -0.66666667]
#  [ 0.66666667  0.33333333 -0.66666667]]

a = np.dot(u, np.diag(s))
a = np.dot(a, vh)
print(a)

[[ 4 11 14]
 [ 8  7 -2]]
(2, 2)
[[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
(2,)
[[18.97366596  0.        ]
 [ 0.          9.48683298]]
(2, 3)
[[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]
[[ 4. 11. 14.]
 [ 8.  7. -2.]]


In [11]:
A = np.array([[1, 1], [1, -2], [2, 1]])
print(A)
# [[ 1  1]
#  [ 1 -2]
#  [ 2  1]]

u, s, v = np.linalg.svd(A, full_matrices = False)
print(u.shape)
print(u)
# (3, 2)
# [[-5.34522484e-01 -1.11022302e-16]
#  [ 2.67261242e-01 -9.48683298e-01]
#  [-8.01783726e-01 -3.16227766e-01]]

print(s.shape)
print(np.diag(s)) # r(A) = 2,故只有两个奇异值
# (2,)
# [[2.64575131 0.        ]
#  [0.         2.23606798]]

print(v.shape)
print(v)
# (2, 2)
# [[-0.70710678 -0.70710678]
#  [-0.70710678  0.70710678]]

a = np.dot(np.dot(u, np.diag(s)), v)
print(a)
# [[ 1.  1.]
#  [ 1. -2.]
#  [ 2.  1.]]

[[ 1  1]
 [ 1 -2]
 [ 2  1]]
(3, 2)
[[-5.34522484e-01 -1.11022302e-16]
 [ 2.67261242e-01 -9.48683298e-01]
 [-8.01783726e-01 -3.16227766e-01]]
(2,)
[[2.64575131 0.        ]
 [0.         2.23606798]]
(2, 2)
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[[ 1.  1.]
 [ 1. -2.]
 [ 2.  1.]]


## QR分解

- `q, r = numpy.linalg.qr(a, mode = 'reduced')` 计算矩阵`a`的QR分解
    - `a` 是一个(M, N)的待分解矩阵
    - `mode = reduced` 返回(M, N)的列向量两两正交的矩阵`q`，和(N, N)的三角阵`r`(Reduced QR分解)
    - `mode = complete`返回(M, M)的正交矩阵`q`，和(M, N)的三角阵`r`(Full QR分解)

In [14]:
A = np.array([[2, -2, 3], [1, 1, 1], [1, 3, -1]])
print(A)

q, r = np.linalg.qr(A)
print(q.shape)
print(q)

print(r.shape)
print(r)

print(np.dot(q, r))

a = np.allclose(np.dot(q.T, q), np.eye(3))
print(a)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]
(3, 3)
[[-0.81649658  0.53452248  0.21821789]
 [-0.40824829 -0.26726124 -0.87287156]
 [-0.40824829 -0.80178373  0.43643578]]
(3, 3)
[[-2.44948974  0.         -2.44948974]
 [ 0.         -3.74165739  2.13808994]
 [ 0.          0.         -0.65465367]]
[[ 2. -2.  3.]
 [ 1.  1.  1.]
 [ 1.  3. -1.]]
True


In [17]:
A = np.array([[1, 1], [1, -2], [2, 1]])
print(A)

q, r = np.linalg.qr(A, mode = 'complete')
print(q.shape)
print(q)

print(r.shape)
print(r)

print(np.dot(q, r))

print(np.allclose(np.dot(q.T, q), np.eye(3)))

[[ 1  1]
 [ 1 -2]
 [ 2  1]]
(3, 3)
[[-0.40824829  0.34503278 -0.84515425]
 [-0.40824829 -0.89708523 -0.16903085]
 [-0.81649658  0.27602622  0.50709255]]
(3, 2)
[[-2.44948974 -0.40824829]
 [ 0.          2.41522946]
 [ 0.          0.        ]]
[[ 1.  1.]
 [ 1. -2.]
 [ 2.  1.]]
True


In [18]:
A = np.array([[1, 1], [1, -2], [2, 1]])
print(A)
# [[ 1  1]
#  [ 1 -2]
#  [ 2  1]]

q, r = np.linalg.qr(A)
print(q.shape)  # (3, 2)
print(q)
# [[-0.40824829  0.34503278]
#  [-0.40824829 -0.89708523]
#  [-0.81649658  0.27602622]]

print(r.shape)  # (2, 2)
print(r)
# [[-2.44948974 -0.40824829]
#  [ 0.          2.41522946]]

print(np.dot(q, r))
# [[ 1.  1.]
#  [ 1. -2.]
#  [ 2.  1.]]

a = np.allclose(np.dot(q.T, q), np.eye(2))
print(a)  # True   （说明q为正交矩阵）

[[ 1  1]
 [ 1 -2]
 [ 2  1]]
(3, 2)
[[-0.40824829  0.34503278]
 [-0.40824829 -0.89708523]
 [-0.81649658  0.27602622]]
(2, 2)
[[-2.44948974 -0.40824829]
 [ 0.          2.41522946]]
[[ 1.  1.]
 [ 1. -2.]
 [ 2.  1.]]
True


## Cholesky分解

- `L = npmpy.linalg.cholesky(a)` 返回正定矩阵`a`的Cholesky分解 `a = L * L.T`其中`L`是下三角

In [19]:
A = np.array([[1, 1, 1, 1], [1, 3, 3, 3],
              [1, 3, 5, 5], [1, 3, 5, 7]])
print(A)
# [[1 1 1 1]
#  [1 3 3 3]
#  [1 3 5 5]
#  [1 3 5 7]]

print(np.linalg.eigvals(A)) # 特征值

L = np.linalg.cholesky(A)
print(L)

print(np.dot(L, L.T))

[[1 1 1 1]
 [1 3 3 3]
 [1 3 5 5]
 [1 3 5 7]]
[13.13707118  1.6199144   0.51978306  0.72323135]
[[1.         0.         0.         0.        ]
 [1.         1.41421356 0.         0.        ]
 [1.         1.41421356 1.41421356 0.        ]
 [1.         1.41421356 1.41421356 1.41421356]]
[[1. 1. 1. 1.]
 [1. 3. 3. 3.]
 [1. 3. 5. 5.]
 [1. 3. 5. 7.]]


## 范数和其他数字

###矩阵的范数
- `numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)` 计算向量或者矩阵的范数。
根据`ord`参数的不同，计算不同的范数：

In [20]:
x = np.array([1, 2, 3, 4])

print(np.linalg.norm(x, ord=1)) 
# 10.0
print(np.sum(np.abs(x)))  
# 10

print(np.linalg.norm(x, ord=2))  
# 5.477225575051661
print(np.sum(np.abs(x) ** 2) ** 0.5)  
# 5.477225575051661

print(np.linalg.norm(x, ord=-np.inf))  
# 1.0
print(np.min(np.abs(x)))  
# 1

print(np.linalg.norm(x, ord=np.inf))  
# 4.0
print(np.max(np.abs(x)))  
# 4

10.0
10
5.477225575051661
5.477225575051661
1.0
1
4.0
4


In [21]:
A = np.array([[1, 2, 3, 4], [2, 3, 5, 8],
              [1, 3, 5, 7], [3, 4, 7, 11]])

print(A)
# [[ 1  2  3  4]
#  [ 2  3  5  8]
#  [ 1  3  5  7]
#  [ 3  4  7 11]]

print(np.linalg.norm(A, ord=1))  # 30.0
print(np.max(np.sum(A, axis=0)))  # 30

print(np.linalg.norm(A, ord=2))  
# 20.24345358700576
print(np.max(np.linalg.svd(A, compute_uv=False)))  
# 20.24345358700576

print(np.linalg.norm(A, ord=np.inf))  # 25.0
print(np.max(np.sum(A, axis=1)))  # 25

print(np.linalg.norm(A, ord='fro'))  
# 20.273134932713294
print(np.sqrt(np.trace(np.dot(A.T, A))))  
# 20.273134932713294

[[ 1  2  3  4]
 [ 2  3  5  8]
 [ 1  3  5  7]
 [ 3  4  7 11]]
30.0
30
20.243453587005757
20.243453587005757
25.0
25
20.273134932713294
20.273134932713294


### 方阵的行列式

- `numpy.linalg.det(a)`计算行列式

In [24]:
x = np.array([[1, 2], [3, 4]])
print(x)

print(np.linalg.det(x))

[[1 2]
 [3 4]]
-2.0000000000000004


### 矩阵的秩

- `numpy.linalg.matrix_rank(M, tol = None, hermitian = False)`返回矩阵的秩


In [26]:
i = np.eye(3)
print(i)
print(np.linalg.matrix_rank(i))

i[1, 1] = 0
print(np.linalg.matrix_rank(i))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3
2


### 矩阵的迹

- `numpy.trace(a, offset = 0, axis1 = 0, axis2 = 1, dtype = None, out = None)` 方阵的迹就是主对角线的和

In [28]:
x = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])

y = np.array([[5, 4, 2], [1, 7, 9], [0, 4, 5]])

print(np.trace(x))

print(np.trace(np.transpose(x)))

print(np.trace(x + y))

print(np.trace(x) + np.trace(y))


13
13
30
30


## 解方程和逆矩阵

### 逆矩阵(inverse matrix)

设 A 是数域上的一个 n 阶矩阵，若在相同数域上存在另一个 n 阶矩阵 B，使得：`AB=BA=E`（E 为单位矩阵），则我们称 B 是 A 的逆矩阵，而 A 则被称为可逆矩阵。

- `numpy.linalg.inv(a)` 计算矩阵`a`的逆矩阵（矩阵可逆的充要条件：`det(a) != 0`，或者`a`满秩）。
【例】计算矩阵的逆矩阵。

In [36]:
A = np.array([[1, -2, 1], [0, 2, -1], [1, 1, -2]])
A_det = np.linalg.det(A)
print(A_det)

A_inverse = np.linalg.inv(A)
print(A_inverse)

x = np.allclose(np.dot(A_inverse, A), np.eye(3))
print(x)

A_companion = A_inverse * A_det
print(A_companion)

print(np.allclose(np.dot(A_companion, A), A_det * np.eye(3)))

-3.0000000000000004
[[ 1.          1.          0.        ]
 [ 0.33333333  1.         -0.33333333]
 [ 0.66666667  1.         -0.66666667]]
True
[[-3. -3. -0.]
 [-1. -3.  1.]
 [-2. -3.  2.]]
True


###   求解线性方程组

- `numpy.linalg.solve(a, b)` 求解线性方程组或矩阵方程

In [38]:
# x + 2y + z = 7
# 2x - y + 3z = 7
# 3x + y + 2z = 18

A = np.array([[1, 2, 1], [2, -1, 3], [3, 1, 2]])
B = np.array([7, 7, 18])
print(np.linalg.solve(A, B))

x = np.linalg.inv(A).dot(B)
print(x)

print(np.allclose(np.dot(A, x), B))

[ 7.  1. -2.]
[ 7.  1. -2.]
True


In [40]:
a, b = np.linalg.eig(A)
print(a, b)

[ 4.7553803 +0.j         -1.37769015+0.45260477j -1.37769015-0.45260477j] [[ 0.4704336 +0.j          0.66245383+0.j          0.66245383-0.j        ]
 [ 0.5308921 +0.j         -0.58811834+0.20733017j -0.58811834-0.20733017j]
 [ 0.7048729 +0.j         -0.39887326-0.11483058j -0.39887326+0.11483058j]]
